services:
  replica1_db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: replica1_db
    networks:
      - db_network

  replica2_db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: replica2_db
    networks:
      - db_network

  replica3_db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: replica3_db
    networks:
      - db_network

  replica4_db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: replica4_db
    networks:
      - db_network

  replica5_db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: replica5_db
    networks:
      - db_network
      
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - db_network
    depends_on:
      - replica1_db
      - replica2_db

networks:
  db_network:
    external: true
