services:
  replica1_db:
    build:
      context: .
      dockerfile: dockerfile
    #image: postgres:14
    container_name: replica1_db
    ports:
      - "5433:5432"
    # volumes:
    #   - replica1_data:/var/lib/postgresql/data
    networks:
      - db_network
  replica2_db:
    build:
      context: .
      dockerfile: dockerfile
    #image: postgres:14
    container_name: replica2_db
    ports:
      - "5434:5432"
    # volumes:
    #   - replica2_data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
