services:
  master_db:
    image: postgres:14
    container_name: master_db
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: masterpassword
      POSTGRES_DB: master_db
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    networks:
      - db_network

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    environment:
      DATABASE_URL: "postgresql://master:masterpassword@haproxy:5003/master_db"
      PGBOUNCER_ADMIN_USER: "admin"
      PGBOUNCER_ADMIN_PASSWORD: "adminpassword"
      PGBOUNCER_POOL_MODE: "transaction"
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - db_network

volumes:
  master_data:

networks:
  db_network:
    external: true
